# Generated by Django 5.1.5 on 2025-01-29 18:57

import django.db.models.deletion
import django.utils.timezone
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=myapp.models.one_month_ago)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('api_key', models.CharField(max_length=100)),
                ('polygon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.polygon')),
            ],
        ),
    ]
