# Generated by Django 5.1.5 on 2025-01-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('collection', models.CharField(max_length=100)),
                ('badge', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.IntegerField()),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img_url', models.URLField()),
                ('link', models.URLField()),
            ],
        ),
    ]
