# Generated by Django 5.1.5 on 2025-01-31 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_crop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='historical_prices',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='image',
        ),
        migrations.CreateModel(
            name='HistoricalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_prices', to='myapp.crop')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
