# Generated by Django 5.1.7 on 2025-03-20 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_resourceitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantHealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_type', models.CharField(max_length=100)),
                ('disease_detected', models.CharField(max_length=200)),
                ('confidence_level', models.CharField(max_length=50)),
                ('precautions', models.TextField()),
                ('solution', models.TextField()),
                ('plant_health', models.CharField(choices=[('Healthy', 'Healthy'), ('Affected', 'Affected')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='plant_health_reports/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
